version: '3.3'
services:

  ccda-hl7-fhir:
    build:
      context: .
    image: ccda-hl7-fhir:iris
    hostname: ccda-hl7-fhir
    ports:
    - "51776:51773" # 51773 is the superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
    # - type: bind
    #   source: ./sampleFiles
    #   target: /home/irisowner/src/sampleFiles
    - type: bind
      source: ./in
      target: /home/irisowner/in
    - type: bind
      source: ./out
      target: /home/irisowner/out
