Class FHIRDemo.Msg.AppointmentRequest Extends (Ens.Request, FHIRDemo.Obj.RendezVous, %JSON.Adaptor)
{

Storage Default
{
<Data name="AppointmentRequestDefaultData">
<Subscript>"AppointmentRequest"</Subscript>
<Value name="1">
<Value>Patient</Value>
</Value>
<Value name="2">
<Value>StartDate</Value>
</Value>
<Value name="3">
<Value>EndDate</Value>
</Value>
<Value name="4">
<Value>Status</Value>
</Value>
<Value name="5">
<Value>EncounterNumber</Value>
</Value>
<Value name="6">
<Value>Encounters</Value>
</Value>
<Value name="7">
<Value>Appointments</Value>
</Value>
<Value name="8">
<Value>Encounter</Value>
</Value>
<Value name="9">
<Value>Appointment</Value>
</Value>
</Data>
<DefaultData>AppointmentRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
